normalization_param:
- - 0.8799755948718553 
  - -0.4399950346571797
- - 13.329505331269239
  - 5.928417768201435
- - 1.551722900341092
  - -0.7026659325952356
- - 11.475635423740737
  - -7.294465531916838
- - 5.633923101737608
  - -3.037661500772959
- - 6.72787847110431
  - -3.131467093743139
- - 16.372132319215105
  - -8.143256105258684
# - - 0.8 # 7 steering velocity
#   - -0.4
- - 6.0 # 7 steering velocity
  - -3.0
- - 7.0 # 8 acceleration
  - -3.5 
# - - 2.0 # 8 acceleration
#   - -1 
- - 400 # 9 frenet s
  - 0
- - 8 # 10 frenet ey
  - -4
- - 3.14 # 11 frenet yaw
  - -3.14
- - 45 # 12 velocity
  - 0
- - 0.83 # 13 steering angle
  - -0.4189
# - - 1.82 # 13 steering angle
#   - -0.910
- - 50 # 14 value function
  - -50

